General go dependency update.
go version go1.5 linux/amd64
Mon Nov  2 13:53:30 PST 2015

diff --git a/godeps/src/github.com/coreos/etcd/test b/godeps/src/github.com/coreos/etcd/test
--- a/godeps/src/github.com/coreos/etcd/test
+++ b/godeps/src/github.com/coreos/etcd/test
@@ -16,7 +16,7 @@ COVER=${COVER:-"-cover"}
 source ./build
 
 # Hack: gofmt ./ will recursively check the .git directory. So use *.go for gofmt.
-TESTABLE_AND_FORMATTABLE="client discovery error etcdctl/command etcdmain etcdserver etcdserver/auth etcdserver/etcdhttp etcdserver/etcdhttp/httptypes pkg/fileutil pkg/flags pkg/idutil pkg/ioutil pkg/netutil pkg/osutil pkg/pbutil pkg/types pkg/transport pkg/wait proxy raft snap storage store version wal"
+TESTABLE_AND_FORMATTABLE="client discovery error etcdctl/command etcdmain etcdserver etcdserver/auth etcdserver/etcdhttp etcdserver/etcdhttp/httptypes pkg/fileutil pkg/flags pkg/idutil pkg/ioutil pkg/netutil pkg/osutil pkg/pbutil pkg/types pkg/transport pkg/wait proxy raft snap storage storage/backend store version wal"
 # TODO: add it to race testing when the issue is resolved
 # https://github.com/golang/go/issues/9946
 NO_RACE_TESTABLE="rafthttp"
@@ -74,13 +74,23 @@ if [ -n "${vetRes}" ]; then
 	exit 255
 fi
 
-if command -v go-nyet >/dev/null 2>&1; then
-  echo "Checking go-nyet..."
-  nyetRes=$(go-nyet -exitWith 0 $FMT)
-  if [ -n "${nyetRes}" ]; then
-          echo -e "go-nyet checking failed:\n${nyetRes}"
-          exit 255
-  fi
+echo "Checking govet -shadow..."
+for path in $FMT; do
+	vetRes=$(go tool vet -shadow ${path})
+	if [ -n "${vetRes}" ]; then
+		echo -e "govet checking ${path} failed:\n${vetRes}"
+		exit 255
+	fi
+done
+
+
+echo "Checking for license header..."
+licRes=$(for file in $(find . -type f -iname '*.go' ! -path './Godeps/*'); do
+		head -n3 "${file}" | grep -Eq "(Copyright|generated|GENERATED)" || echo -e "  ${file}"
+	done;)
+if [ -n "${licRes}" ]; then 
+	echo -e "license header checking failed:\n${licRes}"
+	exit 255
 fi
 
 echo "Success"
